### ISSUE TITLE
TASK [app-server : Place GC3Pie configuration file] fails on deploy

### ISSUE THREAD

**Issue by jluethi** [TissueMAPS/TmDeploy#21]
I'm working on the current develop branch of TmDeploy (a0cbbe3f45d2de64b0fde145d4d7c7b52bd79ff4).
When I deploy a newly launched VM in science cloud, I get the following error that seems to be related to a GC3Pie configuration file:
`TASK [app-server : Place GC3Pie configuration file] *********************************************************************************************************************************
fatal: [joel-tm-standalone-server-001]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleError: template error while templating string: unexpected '}', expected ')'. String: [auth/noauth]\ntype=none\n\n[resource/localhost]\nenabled={{ (not cluster_mode)|lower }}\ntype=shellcmd\nspooldir=/var/tmp\ntransport=local\nauth=noauth\narchitecture=x64_64\nmax_cores={{ tm_compute_cores }}\nmax_cores_per_job={{ tm_compute_cores }}\nmax_memory_per_core={{ tm_compute_memory }} MB\nmax_walltime=48 hours\noverride={{ (tm_compute_autodiscover)|lower }}\n\n[resource/cluster]\nenabled={{ cluster_mode|lower }}\ntype=slurm\nfrontend={{ ansible_hostname }}\ntransport=local\nauth=noauth\narchitecture=x86_64\nmax_cores={{ tm_compute_cores|int * tm_compute_nodes|int }}\nmax_cores_per_job={{ tm_compute_cores }}\nmax_memory_per_core={{ (tm_compute_memory }} MB\nmax_walltime=10 days\n"}`

@riccardomurri How do I fix this configuration file so that there is no unexpected '}'? Have you seen this issue before? Does this depend on the gc3pie version being used and how would I change that?

**Comment by jluethi** [comment]
@sparkvilla Have you seen this before?

**Comment by riccardomurri** [comment]
hi @jluethi the error is in this part of the template:

    max_memory_per_core={{ (tm_compute_memory }}

it should be::

    max_memory_per_core={{ tm_compute_memory }}

i.e., removing the spurious initial `(` -- or add a closing `)`

**Comment by riccardomurri** [comment]
Fixed in the "develop" branch.

**Comment by jluethi** [comment]
Thanks a lot for the quick fix @riccardomurri ! Now it's working, the issue can be closed.
