### ISSUE TITLE
setting `PYTHONPATH` in `~/.bashrc` breaks Python3 programs

### ISSUE THREAD

**Issue by riccardomurri** [TissueMAPS/TmDeploy#4]
With the current playbooks, user `tissuemaps` sets `PYTHONPATH` in the
environment via `$HOME/.bashrc`::

    tissuemaps@riccardo-test-foobar-001:~$ cat .bashrc 
    ...
    export PYTHONPATH=/home/tissuemaps/.local/lib/python2.7/site-packages:$PYTHONPATH
    export PYTHONPATH=/usr/local/lib/python2.7/dist-packages:$PYTHONPATH
    ...

However, since that setting is Python2-specific, it breaks system-level Python3
scripts like e.g. `command-not-found`::

    tissuemaps@riccardo-test-foobar-001:~$ non-existing-cmd
    Traceback (most recent call last):
      File "/usr/lib/command-not-found", line 23, in <module>
        import gettext
      File "/usr/lib/python3.5/gettext.py", line 49, in <module>
        import locale, copy, io, os, re, struct, sys
      File "/usr/lib/python3.5/locale.py", line 16, in <module>
        import re
      File "/usr/lib/python3.5/re.py", line 335, in <module>
        import copyreg
      File "/home/tissuemaps/.local/lib/python2.7/site-packages/copyreg/__init__.py", line 7, in <module>
        raise ImportError('This package should not be accessible on Python 3. '
    ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.

The good news is that setting `PYTHONPATH` in that way is not necessary, as all
values are already in the default search path, see:
https://docs.python.org/3/library/site.html#site.USER_SITE

**Comment by HackerMD** [comment]
`PYTHONPATH` has been removed from `~/.bashrc` with 95dffc969d4721afd594471aa8fd4789a5ce5cfc.
